🚑 :: secret key 재 생성 및 gitignore 처리
Almaeng-i/GuHwangJagMul-Server pull request #9
Opened 2024-03-13 23:20 UTC by MinnSeoo

## 💡 개요
secret key를 재 생성후 ignore 처리를 하였습니다.

## 📃 작업내용
secret key를 재 성성후 secret.json에 저장하여 해당 파일을 ignore 처리를 하였습니다.

## 🔀 변경사항

## 🙋‍♂️ 질문사항

## 🎸 기타

2024-03-13 23:32 UTC, onee-only commented on GHJM/settings.py
> +    secrets = json.loads(f.read())
secrets 스코프는 with 안에 한정 되어 있나요? 아니면 global인가요?

2024-03-13 23:32 UTC, onee-only commented on GHJM/settings.py
> +def get_secret(setting, secrets=secrets):
만약 secrets 스코프가 global이라면 argument로 남겨주거나 아예 받지 않는 것이 좋아 보여요!

2024-03-13 23:43 UTC, MinnSeoo commented on GHJM/settings.py
> +    secrets = json.loads(f.read())
global 인것 같아요..!

2024-03-13 23:43 UTC, MinnSeoo commented on GHJM/settings.py
> +    secrets = json.loads(f.read())
global 인것 같아요..!

2024-03-13 23:45 UTC, MinnSeoo commented on GHJM/settings.py
> +def get_secret(setting, secrets=secrets):
> 만약 secrets 스코프가 global이라면 argument로 남겨주거나 아예 받지 않는 것이 좋아 보여요!

아하.. 혹시 왜 이렇게 생각하셨는지 알려주실 수 있을까요??

2024-03-13 23:53 UTC, onee-only commented on GHJM/settings.py
> +def get_secret(setting, secrets=secrets):
global이라면 get_secret 안에서 직접 참조할 수 있기 때문에 받지 않아도 된다고 생각했고,

혹은 함수가 아래와 같이 명시적으로 setting을 받아서 결괏값을 반환한다면 더 코드가 명확해진다고 생각했어요.

```python
get_secret(secrets, "SECRET_KEY")
```

2024-03-14 00:22 UTC, onee-only requested changes

2024-03-14 00:22 UTC, onee-only commented on GHJM/settings.py
> +def get_secret(setting, secrets):
argument와 parameter의 순서가 맞지 않아요. 둘 중 하나의 순서를 바꾸지 않으면 runtime error가 발생할 것으로 보여요.

2024-03-14 00:24 UTC, MinnSeoo commented on GHJM/settings.py
> +def get_secret(setting, secrets):
앗... 제가 잘 확인하지 못했네요. 바로 수정하겠습니다!

2024-03-14 01:43 UTC, onee-only approved these changes
👍

2024-03-14 01:51 UTC, merged